# Generated by Django 5.2.1 on 2025-05-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='stock',
        ),
    ]
