# Generated by Django 5.2.1 on 2025-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
