# Generated by Django 5.2.1 on 2025-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_alter_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('hold', 'On Hold')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
